# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The White Jersey
email: jamesmoffat@outlook.com
Name: James Moffat
description: A very ocassional cyclist
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thewhitejersey.com" # the base hostname & protocol for your site
twitter_username: jsmoffat

# Build settings
markdown: kramdown
